### ISSUE TITLE
Link to blog in README.md does not work

### ISSUE THREAD

**Issue by rdlarah** [jiridj/hugo-macos-terminal#1]
Hi Jiri,

the README hints at more information being available on you blog.

The link, however, doesn't work in most browsers. It seems like the SSL certificate isn't valid. Firefox gives an `SSL_ERROR_INTERNAL_ERROR_ALERT` for  jiridj.be

Please consider either fixing the site or adding the information to this repo.

Cheers
Harald

**Comment by jiridj** [comment]
That blog is no longer online. But I've pulled the extra info from the old repo and added it to the README. Have fun!

**Comment by rdlarah** [comment]
Thank you.
